# Experiment 1
# Evaluating efficacy of multi-token regularization during pretraining and finetuning
preambles:
  glong:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long"
    - "#SBATCH --gres=gpu:rtx8000:1"
    - "#SBATCH --mem=32G"
    - "#SBATCH --cpus-per-task=8"
    - "#SBATCH --nodes=1"
    - "source /home/mila/m/marawan.gamal/scratch/mtl/.venv/bin/activate"

group:
  name: "main"
  type: parallel
  jobs:

    # Shakespeare | None 
    # - group:
    #     name: "shakespeare::none"
    #     type: sweep
    #     preamble: glong
    #     sweep:
    #       lr: [1e-3]
    #     sweep_template: "python train.py --lr {lr}"

    # Shakespeare | CP
    - group:
        name: "shakespeare::cp"
        type: sweep
        preamble: glong
        sweep:
          lr: [1e-3]
          lm_head: ["cp"]
          lm_head_pos_func: ["abs"]
          lm_head_rank: [2]
          lm_head_horizon: [4]
        sweep_template: "python train.py --lr {lr} --lm_head {lm_head} --lm_head_pos_func {lm_head_pos_func} --lm_head_rank {lm_head_rank} --lm_head_horizon {lm_head_horizon}"


    # Shakespeare | CP
    - group:
        name: "shakespeare::moe"
        type: sweep
        preamble: glong
        sweep:
          lr: [1e-3]
          lm_head: ["moe"]
          lm_head_pos_func: ["abs"]
          lm_head_rank: [2]
          lm_head_horizon: [4]
        sweep_template: "python train.py --lr {lr} --lm_head {lm_head} --lm_head_pos_func {lm_head_pos_func} --lm_head_rank {lm_head_rank} --lm_head_horizon {lm_head_horizon}"



    # Shakespeare | CP
    - group:
        name: "shakespeare::mps"
        type: sweep
        preamble: glong
        sweep:
          lr: [1e-3]
          lm_head: ["mps"]
          lm_head_pos_func: ["abs"]
          lm_head_rank: [2]
          lm_head_horizon: [4]
        sweep_template: "python train.py --lr {lr} --lm_head {lm_head} --lm_head_pos_func {lm_head_pos_func} --lm_head_rank {lm_head_rank} --lm_head_horizon {lm_head_horizon}"

